/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/w9CvBjGCMs3
 */
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"

export function Search() {
  return (
    <div className="container mx-auto px-4 py-6 flex flex-col items-center">
      <h1 className="text-3xl font-bold mb-8 text-center">LibreScholar</h1>
      <div className="flex w-full max-w-md items-center space-x-2 mb-8 justify-center">
        <Input className="w-full" placeholder="Enter research question" type="text" />
        <Button type="submit">Search</Button>
      </div>
      <h2 className="text-2xl font-semibold mb-4 text-center">Relevant Scientific Publications:</h2>
      <ul className="list-disc list-inside mb-6 text-center">
        <li className="mb-2">
          J Tan, C Liang, H Xie, Q Xu, J Hu, H Zhu (2022). <b>Justitia: Software Multi-Tenancy in Hardware Kernel-Bypass Networks</b>. In <i>NSDI 22</i>.
        </li>
      </ul>
      <div className="grid grid-cols-1 gap-6 justify-items-center" />
    </div>
  )
}
